# Generated by Django 3.1.6 on 2021-03-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_num', models.CharField(max_length=128)),
                ('waybill_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
