# Generated by Django 3.1.6 on 2021-03-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistic_tracking', models.CharField(help_text='Генерируется в системе', max_length=32, unique=True, verbose_name='Номер заявки в системе транспортной компании')),
                ('client_tracking', models.CharField(help_text='Уникальный для каждого заказа', max_length=64, verbose_name='Номер заявки в системе отправителя')),
                ('client_name', models.CharField(blank=True, help_text='Название организации', max_length=264, verbose_name='Грузоотправитель')),
                ('shipping_date', models.DateField(null=True, verbose_name='Ожидаемая дата подачи транспорта')),
                ('shipping_time', models.TimeField(null=True, verbose_name='Ожидаемое время подачи транспорта')),
                ('shipping_from', models.TextField(blank=True, verbose_name='Адрес загрузки транспорта')),
                ('shipping_car_type', models.CharField(max_length=264, verbose_name='Формат предоставлемой машины')),
                ('shipping_method', models.CharField(default='auto', help_text='По умолчанию: auto', max_length=128, verbose_name='Способ доставки')),
                ('recipient_order_num', models.CharField(max_length=64, verbose_name='Номер заказа клиента')),
                ('cargo_description', models.CharField(blank=True, max_length=264, verbose_name='Груз: описание')),
                ('cargo_pallet', models.IntegerField(null=True, verbose_name='Груз: кол-во, паллет')),
                ('cargo_qty', models.IntegerField(null=True, verbose_name='Груз: кол-во мест')),
                ('cargo_weight', models.FloatField(help_text='кг', null=True, verbose_name='Груз: масса')),
                ('cargo_price', models.CharField(blank=True, help_text='руб.', max_length=128, verbose_name='Стоимость груза')),
                ('recipient_zip', models.CharField(blank=True, max_length=128, verbose_name='Адрес получателя: почтовый индекс')),
                ('recipient_city', models.CharField(blank=True, max_length=128, verbose_name='Адрес получателя: город')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Адрес получателя: электронная почта')),
                ('recipient_area', models.CharField(blank=True, max_length=128, verbose_name='Адрес получателя: область')),
                ('recipient_address', models.CharField(blank=True, max_length=256, verbose_name='Адрес получателя: адрес')),
                ('recipient_address_comment', models.TextField(blank=True, verbose_name='Адрес получателя: комментарий')),
                ('recipient_phone', models.TextField(blank=True, verbose_name='Телефон получателя')),
                ('recipient_name', models.CharField(blank=True, max_length=264, verbose_name='ФИО получателя')),
                ('recipient_name2', models.CharField(blank=True, max_length=264, verbose_name='ФИО получателя. Альтернативный получатель')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения заказа')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии к заказу')),
                ('company', models.ForeignKey(help_text='Компания, к которой принадлежит пользователь, создавший документ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='Компания')),
                ('recipient_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='companies.company', verbose_name='Получатель в базе клиента')),
            ],
        ),
    ]
