# Generated by Django 3.1.6 on 2021-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='recipient_company',
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Идентификатор в базе клиента'),
        ),
    ]
