# Generated by Django 3.1.6 on 2021-03-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210305_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Идентификатор получателя в базе клиента'),
        ),
    ]
